add-docker (ТЗ 16) v1.0
Lilyziz/java-shareit pull request #4
Opened 2023-08-24 18:24 UTC by Lilyziz

Я пытаюсь собрать это ТЗ на коленке, а может даже и на коленях. Я не могу на свой комп установить докер, никто не смог помочь. Прямая цитата наставника: "выглядит так, что без hyper-v вряд ли что-то получится придумать".  Поэтому молюсь, чтоб лунная призма помогла сдать этот проект....

2023-08-24 20:16 UTC, Lilyziz commented
Я, наверное, очень наглею, но мне нужна подсказка! Я не понимаю куда мне копать. Я сделала всё по наитию, сообщениям в общих чатах и так далее.

2023-08-24 21:29 UTC, Lilyziz commented
Я увидела лишь одного человека, который имеет проблему, которая похожа на мою, да и то на другой винде. П - паника.

2023-08-25 13:51 UTC, Lilyziz commented
Пол дня переписываюсь с уже новой когортой, подкинули пару идей, буду пробовать ночью

2023-08-25 20:00 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-25 20:00 UTC, FanaticFiz commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Валидация только на `gaeway`

2023-08-25 20:00 UTC, FanaticFiz commented on server/pom.xml
> +        <java.version>11</java.version>
Эти параметры указаны у родителя - тут можно не повторять

2023-08-25 20:00 UTC, FanaticFiz commented on server/src/main/resources/application.properties
> +spring.datasource.driverClassName=org.postgresql.Driver
Ты эти свойства просто задублировала, уже созданы подобные...
их нужно удалить или разделить по профилям.

2023-08-25 20:00 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/State.java
> +public enum State {
Класс целиком не используется, удалить?

2023-08-25 20:00 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/State.java
> +    REJECTED;
Вот тут точки с запятой не нужно после REJECTED

2023-08-25 21:21 UTC, Lilyziz commented
Проблема в том, что я не могу у себя это запустить, поэтому не понимаю как это должно выглядеть и как запускаться. Мне один студентов новой когорты предложил делать это через Virtual Box. 
Тесты отрабатывают только те, которые рассчитаны на валидацию в gateway и всё.

2023-08-26 04:50 UTC, Lilyziz commented
Вообщем я ещё раз всё переделала, разобралась вроде бы. Не с докером, а с проектом.

2023-08-26 13:50 UTC, FanaticFiz approved these changes

2023-08-26 18:57 UTC, merged